// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220202500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique()
                        .HasFilter("[ClienteId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NroCelular")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Preferencias")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ClienteId")
                        .HasName("PK__Clientes__71ABD08713A28857");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("DomainLayer.Models.EstadoTurno", b =>
                {
                    b.Property<int>("EstadoTurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoTurnoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EstadoTurnoId")
                        .HasName("PK__EstadoTu__10C65F06EAEE620F");

                    b.ToTable("EstadoTurno", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.HistorialTurno", b =>
                {
                    b.Property<int>("HistorialTurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialTurnoId"));

                    b.Property<int>("EstadoTurnoActual")
                        .HasColumnType("int");

                    b.Property<int>("EstadoTurnoAnterior")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FechaHoraActual")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaHoraAnterior")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("HistorialTurnoId")
                        .HasName("PK__Historia__1CF9757939A17C0F");

                    b.HasIndex("EstadoTurnoActual");

                    b.HasIndex("EstadoTurnoAnterior");

                    b.HasIndex("TurnoId");

                    b.ToTable("HistorialTurno", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.MetodoPago", b =>
                {
                    b.Property<int>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodoPagoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MetodoPagoId")
                        .HasName("PK__MetodoPa__A8FEAF5471A25E67");

                    b.ToTable("MetodoPago", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<DateTimeOffset>("FechaPago")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(20, 2)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("PagoId")
                        .HasName("PK__Pago__F00B61383B8FEBFF");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("TurnoId");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(20, 2)");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("int");

                    b.HasKey("ServicioId")
                        .HasName("PK__Servicio__D5AEECC205ED5477");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("Servicio", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.TipoServicio", b =>
                {
                    b.Property<int>("TipoServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoServicioId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TipoServicioId")
                        .HasName("PK__TipoServ__BC9FF47D782EAA7F");

                    b.ToTable("TipoServicio", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EstadoTurnoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaTurno")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraTurno")
                        .HasColumnType("time");

                    b.HasKey("TurnoId")
                        .HasName("PK__Turno__AD3E2E9443AF8BC7");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadoTurnoId");

                    b.ToTable("Turno", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.TurnoServicio", b =>
                {
                    b.Property<int>("TurnoServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnoServicioId"));

                    b.Property<decimal>("MontoAplicado")
                        .HasColumnType("decimal(20, 2)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoAplicado")
                        .HasColumnType("int");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("TurnoServicioId")
                        .HasName("PK__TurnoSer__F990823038421B8C");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TurnoId");

                    b.ToTable("TurnoServicio", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.Identity.AppUser", b =>
                {
                    b.HasOne("DomainLayer.Models.Cliente", "Cliente")
                        .WithOne()
                        .HasForeignKey("DAL.Identity.AppUser", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("DomainLayer.Models.HistorialTurno", b =>
                {
                    b.HasOne("DomainLayer.Models.EstadoTurno", "EstadoTurnoActualNavigation")
                        .WithMany("HistorialTurnoEstadoTurnoActualNavigations")
                        .HasForeignKey("EstadoTurnoActual")
                        .IsRequired()
                        .HasConstraintName("FK__Historial__Estad__76619304");

                    b.HasOne("DomainLayer.Models.EstadoTurno", "EstadoTurnoAnteriorNavigation")
                        .WithMany("HistorialTurnoEstadoTurnoAnteriorNavigations")
                        .HasForeignKey("EstadoTurnoAnterior")
                        .IsRequired()
                        .HasConstraintName("FK__Historial__Estad__756D6ECB");

                    b.HasOne("DomainLayer.Models.Turno", "Turno")
                        .WithMany("HistorialTurnos")
                        .HasForeignKey("TurnoId")
                        .IsRequired()
                        .HasConstraintName("FK_Historial_Turno");

                    b.Navigation("EstadoTurnoActualNavigation");

                    b.Navigation("EstadoTurnoAnteriorNavigation");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("DomainLayer.Models.Pago", b =>
                {
                    b.HasOne("DomainLayer.Models.MetodoPago", "MetodoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("MetodoPagoId")
                        .IsRequired()
                        .HasConstraintName("FK__Pago__MetodoPago__70A8B9AE");

                    b.HasOne("DomainLayer.Models.Turno", "Turno")
                        .WithMany("Pagos")
                        .HasForeignKey("TurnoId")
                        .IsRequired()
                        .HasConstraintName("FK__Pago__TurnoId__6FB49575");

                    b.Navigation("MetodoPago");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("DomainLayer.Models.Servicio", b =>
                {
                    b.HasOne("DomainLayer.Models.TipoServicio", "TipoServicio")
                        .WithMany("Servicios")
                        .HasForeignKey("TipoServicioId")
                        .IsRequired()
                        .HasConstraintName("FK_Servicio_TipoServicio");

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("DomainLayer.Models.Turno", b =>
                {
                    b.HasOne("DomainLayer.Models.Cliente", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_Turno_Cliente");

                    b.HasOne("DomainLayer.Models.EstadoTurno", "EstadoTurno")
                        .WithMany("Turnos")
                        .HasForeignKey("EstadoTurnoId")
                        .IsRequired()
                        .HasConstraintName("FK_Turno_EstadoTurno");

                    b.Navigation("Cliente");

                    b.Navigation("EstadoTurno");
                });

            modelBuilder.Entity("DomainLayer.Models.TurnoServicio", b =>
                {
                    b.HasOne("DomainLayer.Models.Servicio", "Servicio")
                        .WithMany("TurnoServicios")
                        .HasForeignKey("ServicioId")
                        .IsRequired()
                        .HasConstraintName("FK__TurnoServ__Servi__6CD828CA");

                    b.HasOne("DomainLayer.Models.Turno", "Turno")
                        .WithMany("TurnoServicios")
                        .HasForeignKey("TurnoId")
                        .IsRequired()
                        .HasConstraintName("FK__TurnoServ__Turno__6BE40491");

                    b.Navigation("Servicio");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainLayer.Models.Cliente", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("DomainLayer.Models.EstadoTurno", b =>
                {
                    b.Navigation("HistorialTurnoEstadoTurnoActualNavigations");

                    b.Navigation("HistorialTurnoEstadoTurnoAnteriorNavigations");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("DomainLayer.Models.MetodoPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("DomainLayer.Models.Servicio", b =>
                {
                    b.Navigation("TurnoServicios");
                });

            modelBuilder.Entity("DomainLayer.Models.TipoServicio", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("DomainLayer.Models.Turno", b =>
                {
                    b.Navigation("HistorialTurnos");

                    b.Navigation("Pagos");

                    b.Navigation("TurnoServicios");
                });
#pragma warning restore 612, 618
        }
    }
}
